### ISSUE TITLE
API: `No 'Access-Control-Allow-Origin' header is present on the requested resource` error

### ISSUE THREAD

**Issue by birbjam** [biocodellc/localcontexts_db#520] opened 2022-04-13 18:27 UTC
Full error message:

> Access to XMLHttpRequest at 'https://anth-ja77-lc-dev-42d5.uc.r.appspot.com/api/v1/projects/16a5280d-69fd-4b41-866d-ad4fc257d513/' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by birbjam** [comment] 2022-04-13 20:17
I think this has been addressed

**Comment by jdeck88** [comment] 2022-12-09 15:32
how did you address this?  still an issue for me as i'm re-writing some of the code inGEOME to access services...

**Comment by birbjam** [comment] 2022-12-09 16:50
@jdeck88 The line `CORS_ORIGIN_ALLOW_ALL = True` already exists in the code can you please send me a code snippet of what you're trying to do?

**Comment by jdeck88** [comment] 2022-12-09 17:09
interesting that i didn't see that in git, but perhaps it is not in the committed code?  are you sure that line is in deployed version?

See the following line... embedded in angularjs so tricky to reproduce but i can try and come up with a working example if you need it
https://github.com/biocodellc/geome-ui/blob/48564d093985ae8b0b8f2bdb5444e626805e5fed/src/app/views/record/record.component.js#L261

**Comment by birbjam** [comment] 2022-12-09 17:19
@jdeck88 
Yes I am sure: https://github.com/biocodellc/localcontexts_db/blob/master/localcontexts/settings.py
Line 238 and this code is up to date with prod.

Is your code up to date with everything in this repo?

In your code for line 259, is there a reason `https:` is not included in this?
`var lcUrl = '//localcontextshub.org/api/v1/projects/' + project.localcontextsId + '/?format=json';`

A working example might be helpful because I can't recreate this error.

**Comment by jdeck88** [comment] 2022-12-09 17:27
i've been playing with this and replaced the angularjs $http.get method with the following:
```
var lcUrl = 'https://localcontextshub.org/api/v1/projects/' + project.localcontextsId + '/?format=json';
var xmlHttp = new XMLHttpRequest();
          xmlHttp.open("GET", lcUrl, false); // false for synchronous request
          xmlHttp.send(null);
          localContextsData = JSON.parse(xmlHttp.responseText)
```
and it works!  there is some setting there that does not like the stricter angularjs methods...The XMLHttpRequest object has different request methods but i couldn't pin down which ones.  :(  In any case, there is now this working example here:

https://geome-db.org/record/ark:~2F21547~2FCpJ2BIOMAR_5001

closing issue again because i do not care to dig any further into CORS policies

**Closed by jdeck88** 2022-12-09 17:27 UTC
Labels: bug, high priority, API
